global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/actuator/metrics'
    scrape_interval: 15s
    static_configs:
      - targets:
        - 'maruchek-blogengine-java.herokuapp.com'
  # - job_name: 'salesforce'
  #       metrics_path: '/services/apexrest/api/v1/prometheus'
  #       scheme: http
  #       static_configs:
  #         - targets: ['test.secure.force.com']
