global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s
    static_configs:
      - targets: ['https://maruchek-blogengine-java.herokuapp.com:8080', '192.168.3.1:8080']
  # - job_name: 'salesforce'
  #       metrics_path: '/services/apexrest/api/v1/prometheus'
  #       scheme: http
  #       static_configs:
  #         - targets: ['test.secure.force.com']
