global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/api/hidden-monitor/prometheus'
    scrape_interval: 15s
    scheme: https
    static_configs:
      - targets:
        - 'zerone-2022-develop.herokuapp.com'
  # - job_name: 'salesforce'
  #       metrics_path: '/services/apexrest/api/v1/prometheus'
  #       scheme: http
  #       static_configs:
  #         - targets: ['test.secure.force.com']
